//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the leg_detector2 package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __leg_detector2__LEGDETECTORCONFIG_H__
#define __leg_detector2__LEGDETECTORCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace leg_detector2
{
  class LegDetectorConfigStatics;
  
  class LegDetectorConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(LegDetectorConfig &config, const LegDetectorConfig &max, const LegDetectorConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const LegDetectorConfig &config1, const LegDetectorConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, LegDetectorConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const LegDetectorConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LegDetectorConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const LegDetectorConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T LegDetectorConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (LegDetectorConfig::* field);

      virtual void clamp(LegDetectorConfig &config, const LegDetectorConfig &max, const LegDetectorConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const LegDetectorConfig &config1, const LegDetectorConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, LegDetectorConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const LegDetectorConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LegDetectorConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const LegDetectorConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 8 "../cfg/LegDetector.cfg"
      double connection_threshold;
//#line 9 "../cfg/LegDetector.cfg"
      int min_points_per_group;
//#line 12 "../cfg/LegDetector.cfg"
      double leg_reliability_limit;
//#line 13 "../cfg/LegDetector.cfg"
      bool publish_legs;
//#line 14 "../cfg/LegDetector.cfg"
      bool publish_people;
//#line 15 "../cfg/LegDetector.cfg"
      bool publish_leg_markers;
//#line 16 "../cfg/LegDetector.cfg"
      bool publish_people_markers;
//#line 18 "../cfg/LegDetector.cfg"
      double no_observation_timeout;
//#line 19 "../cfg/LegDetector.cfg"
      double max_second_leg_age;
//#line 20 "../cfg/LegDetector.cfg"
      double max_track_jump;
//#line 21 "../cfg/LegDetector.cfg"
      double max_meas_jump;
//#line 22 "../cfg/LegDetector.cfg"
      double leg_pair_separation;
//#line 23 "../cfg/LegDetector.cfg"
      std::string fixed_frame;
//#line 25 "../cfg/LegDetector.cfg"
      double kalman_p;
//#line 26 "../cfg/LegDetector.cfg"
      double kalman_q;
//#line 27 "../cfg/LegDetector.cfg"
      double kalman_r;
//#line 28 "../cfg/LegDetector.cfg"
      int kalman_on;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("LegDetectorConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const LegDetectorConfig &__max__ = __getMax__();
      const LegDetectorConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const LegDetectorConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const LegDetectorConfig &__getDefault__();
    static const LegDetectorConfig &__getMax__();
    static const LegDetectorConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const LegDetectorConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void LegDetectorConfig::ParamDescription<std::string>::clamp(LegDetectorConfig &config, const LegDetectorConfig &max, const LegDetectorConfig &min) const
  {
    return;
  }

  class LegDetectorConfigStatics
  {
    friend class LegDetectorConfig;
    
    LegDetectorConfigStatics()
    {
//#line 8 "../cfg/LegDetector.cfg"
      __min__.connection_threshold = 0.0;
//#line 8 "../cfg/LegDetector.cfg"
      __max__.connection_threshold = 0.25;
//#line 8 "../cfg/LegDetector.cfg"
      __default__.connection_threshold = 0.06;
//#line 8 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<double>("connection_threshold", "double", 0, "[m]", "", &LegDetectorConfig::connection_threshold)));
//#line 9 "../cfg/LegDetector.cfg"
      __min__.min_points_per_group = 1;
//#line 9 "../cfg/LegDetector.cfg"
      __max__.min_points_per_group = 20;
//#line 9 "../cfg/LegDetector.cfg"
      __default__.min_points_per_group = 5;
//#line 9 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<int>("min_points_per_group", "int", 0, "", "", &LegDetectorConfig::min_points_per_group)));
//#line 12 "../cfg/LegDetector.cfg"
      __min__.leg_reliability_limit = 0.0;
//#line 12 "../cfg/LegDetector.cfg"
      __max__.leg_reliability_limit = 1.0;
//#line 12 "../cfg/LegDetector.cfg"
      __default__.leg_reliability_limit = 0.7;
//#line 12 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<double>("leg_reliability_limit", "double", 0, "", "", &LegDetectorConfig::leg_reliability_limit)));
//#line 13 "../cfg/LegDetector.cfg"
      __min__.publish_legs = 0;
//#line 13 "../cfg/LegDetector.cfg"
      __max__.publish_legs = 1;
//#line 13 "../cfg/LegDetector.cfg"
      __default__.publish_legs = 1;
//#line 13 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<bool>("publish_legs", "bool", 0, "", "", &LegDetectorConfig::publish_legs)));
//#line 14 "../cfg/LegDetector.cfg"
      __min__.publish_people = 0;
//#line 14 "../cfg/LegDetector.cfg"
      __max__.publish_people = 1;
//#line 14 "../cfg/LegDetector.cfg"
      __default__.publish_people = 1;
//#line 14 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<bool>("publish_people", "bool", 0, "", "", &LegDetectorConfig::publish_people)));
//#line 15 "../cfg/LegDetector.cfg"
      __min__.publish_leg_markers = 0;
//#line 15 "../cfg/LegDetector.cfg"
      __max__.publish_leg_markers = 1;
//#line 15 "../cfg/LegDetector.cfg"
      __default__.publish_leg_markers = 1;
//#line 15 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<bool>("publish_leg_markers", "bool", 0, "", "", &LegDetectorConfig::publish_leg_markers)));
//#line 16 "../cfg/LegDetector.cfg"
      __min__.publish_people_markers = 0;
//#line 16 "../cfg/LegDetector.cfg"
      __max__.publish_people_markers = 1;
//#line 16 "../cfg/LegDetector.cfg"
      __default__.publish_people_markers = 1;
//#line 16 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<bool>("publish_people_markers", "bool", 0, "", "", &LegDetectorConfig::publish_people_markers)));
//#line 18 "../cfg/LegDetector.cfg"
      __min__.no_observation_timeout = 0.0;
//#line 18 "../cfg/LegDetector.cfg"
      __max__.no_observation_timeout = 5.0;
//#line 18 "../cfg/LegDetector.cfg"
      __default__.no_observation_timeout = 0.5;
//#line 18 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<double>("no_observation_timeout", "double", 0, "Timeout tolerance for no observations [s]", "", &LegDetectorConfig::no_observation_timeout)));
//#line 19 "../cfg/LegDetector.cfg"
      __min__.max_second_leg_age = 0.0;
//#line 19 "../cfg/LegDetector.cfg"
      __max__.max_second_leg_age = 5.0;
//#line 19 "../cfg/LegDetector.cfg"
      __default__.max_second_leg_age = 2.0;
//#line 19 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<double>("max_second_leg_age", "double", 0, "[s]", "", &LegDetectorConfig::max_second_leg_age)));
//#line 20 "../cfg/LegDetector.cfg"
      __min__.max_track_jump = 0.0;
//#line 20 "../cfg/LegDetector.cfg"
      __max__.max_track_jump = 5.0;
//#line 20 "../cfg/LegDetector.cfg"
      __default__.max_track_jump = 1.0;
//#line 20 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<double>("max_track_jump", "double", 0, "[m]", "", &LegDetectorConfig::max_track_jump)));
//#line 21 "../cfg/LegDetector.cfg"
      __min__.max_meas_jump = 0.0;
//#line 21 "../cfg/LegDetector.cfg"
      __max__.max_meas_jump = 5.0;
//#line 21 "../cfg/LegDetector.cfg"
      __default__.max_meas_jump = 0.75;
//#line 21 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<double>("max_meas_jump", "double", 0, "[m]", "", &LegDetectorConfig::max_meas_jump)));
//#line 22 "../cfg/LegDetector.cfg"
      __min__.leg_pair_separation = 0.0;
//#line 22 "../cfg/LegDetector.cfg"
      __max__.leg_pair_separation = 2.0;
//#line 22 "../cfg/LegDetector.cfg"
      __default__.leg_pair_separation = 1.0;
//#line 22 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<double>("leg_pair_separation", "double", 0, "[m]", "", &LegDetectorConfig::leg_pair_separation)));
//#line 23 "../cfg/LegDetector.cfg"
      __min__.fixed_frame = "";
//#line 23 "../cfg/LegDetector.cfg"
      __max__.fixed_frame = "";
//#line 23 "../cfg/LegDetector.cfg"
      __default__.fixed_frame = "odom_combined";
//#line 23 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<std::string>("fixed_frame", "str", 0, "Fixed Frame", "", &LegDetectorConfig::fixed_frame)));
//#line 25 "../cfg/LegDetector.cfg"
      __min__.kalman_p = 0.0;
//#line 25 "../cfg/LegDetector.cfg"
      __max__.kalman_p = 10.0;
//#line 25 "../cfg/LegDetector.cfg"
      __default__.kalman_p = 4.0;
//#line 25 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<double>("kalman_p", "double", 0, "", "", &LegDetectorConfig::kalman_p)));
//#line 26 "../cfg/LegDetector.cfg"
      __min__.kalman_q = 0.0;
//#line 26 "../cfg/LegDetector.cfg"
      __max__.kalman_q = 10.0;
//#line 26 "../cfg/LegDetector.cfg"
      __default__.kalman_q = 0.002;
//#line 26 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<double>("kalman_q", "double", 0, "", "", &LegDetectorConfig::kalman_q)));
//#line 27 "../cfg/LegDetector.cfg"
      __min__.kalman_r = 0.0;
//#line 27 "../cfg/LegDetector.cfg"
      __max__.kalman_r = 20.0;
//#line 27 "../cfg/LegDetector.cfg"
      __default__.kalman_r = 10.0;
//#line 27 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<double>("kalman_r", "double", 0, "", "", &LegDetectorConfig::kalman_r)));
//#line 28 "../cfg/LegDetector.cfg"
      __min__.kalman_on = 0;
//#line 28 "../cfg/LegDetector.cfg"
      __max__.kalman_on = 1;
//#line 28 "../cfg/LegDetector.cfg"
      __default__.kalman_on = 1;
//#line 28 "../cfg/LegDetector.cfg"
      __param_descriptions__.push_back(LegDetectorConfig::AbstractParamDescriptionConstPtr(new LegDetectorConfig::ParamDescription<int>("kalman_on", "int", 0, "", "", &LegDetectorConfig::kalman_on)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<LegDetectorConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<LegDetectorConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    LegDetectorConfig __max__;
    LegDetectorConfig __min__;
    LegDetectorConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const LegDetectorConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static LegDetectorConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &LegDetectorConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const LegDetectorConfig &LegDetectorConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const LegDetectorConfig &LegDetectorConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const LegDetectorConfig &LegDetectorConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<LegDetectorConfig::AbstractParamDescriptionConstPtr> &LegDetectorConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const LegDetectorConfigStatics *LegDetectorConfig::__get_statics__()
  {
    const static LegDetectorConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = LegDetectorConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __LEGDETECTORRECONFIGURATOR_H__
