base_local_planner: dwa_local_planner_moving_obs/DWAPlannerMovingObsROS
DWAPlannerMovingObsROS:
  transform_tolerance: 2.0
  world_model: costmap
  sim_time: 4.0
  sim_granularity: 0.025
  vx_samples: 5
  vtheta_samples: 20
  max_vel_x: .55
  min_vel_x: 0.01
  max_trans_vel: .55
  min_trans_vel: 0.01
  max_rot_vel: 2
  min_rot_vel: 0
  xy_goal_tolerance: 0.12
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false
  goal_distance_bias: 24
  path_distance_bias: 32
  occdist_scale: .01
  forward_point_dist: 0.325
  oscillation_reset_dist: 0.05
  acc_lim_th: 40
  acc_lim_x: 6
  acc_lim_y: 0.0
  simple_attractor: false
  max_vel_y: 0
  min_vel_y: 0
  
  vy_samples: 0
  penalise_negetive_x: false
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  controller_frequency: 20
  prune_plan: true


  
