map_type: costmap
transform_tolerance: 2.0
obstacle_range: 2.5
max_obstacle_height: 2.0
raytrace_range: 3.0
inscribed_radius: 0.35
circumscribed_radius: 0.42
inflation_radius: 0.5
cost_scaling_factor: 15.0
lethal_cost_threshold: 100


