#!/bin/bash
#for i in $( ls figures/*.eps); do
#    newname=`echo $i|sed 's/\.eps$//g'`
#    convert $i -quality 100 -density 300 $newname.jpg
#done

#for i in $( ls figures/*.png); do
#    newname=`echo $i|sed 's/\.png$//g'`
#    newname=`echo $newname|sed 's/\estimation$//g'`
#    convert $i -quality 100 -density 300 $newname.jpg
#done

for i in $( ls figures/estimation*.png); do
#for i in `seq 1 131`; do
    number=`echo $i|sed 's/\.png$//g'`
    number=`echo $number|sed 's/figures\/estimation//g'`
    echo $number
    echo $i
    file1="figures/estimation$number.png"
    file2="figures/groundTruth$number.png"
    #echo $file1
    #echo $file2
    newfile=`echo $file1|sed 's/figures\/estimation//g'`
    newfile="figures/composed$newfile"
    #echo $newfile
    convert $file2 $file1 +append $newfile
done

#number=`echo $j|sed 's/\.png$//g'`
#number=`echo $number|sed 's/figures\/estimation//g'`

