/* Auto-generated by genmsg_cpp for file /home/vinay/ROS/ptu_control/msg/PtuGotoGoal.msg */
#ifndef PTU_CONTROL_MESSAGE_PTUGOTOGOAL_H
#define PTU_CONTROL_MESSAGE_PTUGOTOGOAL_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace ptu_control
{
template <class ContainerAllocator>
struct PtuGotoGoal_ : public ros::Message
{
  typedef PtuGotoGoal_<ContainerAllocator> Type;

  PtuGotoGoal_()
  : pan(0.0)
  , tilt(0.0)
  , pan_vel(0.0)
  , tilt_vel(0.0)
  {
  }

  PtuGotoGoal_(const ContainerAllocator& _alloc)
  : pan(0.0)
  , tilt(0.0)
  , pan_vel(0.0)
  , tilt_vel(0.0)
  {
  }

  typedef float _pan_type;
  float pan;

  typedef float _tilt_type;
  float tilt;

  typedef float _pan_vel_type;
  float pan_vel;

  typedef float _tilt_vel_type;
  float tilt_vel;


private:
  static const char* __s_getDataType_() { return "ptu_control/PtuGotoGoal"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "3081c5893ca658a36b6caa436091a00d"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# goal\n\
float32 pan\n\
float32 tilt\n\
float32 pan_vel\n\
float32 tilt_vel\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, pan);
    ros::serialization::serialize(stream, tilt);
    ros::serialization::serialize(stream, pan_vel);
    ros::serialization::serialize(stream, tilt_vel);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, pan);
    ros::serialization::deserialize(stream, tilt);
    ros::serialization::deserialize(stream, pan_vel);
    ros::serialization::deserialize(stream, tilt_vel);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(pan);
    size += ros::serialization::serializationLength(tilt);
    size += ros::serialization::serializationLength(pan_vel);
    size += ros::serialization::serializationLength(tilt_vel);
    return size;
  }

  typedef boost::shared_ptr< ::ptu_control::PtuGotoGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ptu_control::PtuGotoGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct PtuGotoGoal
typedef  ::ptu_control::PtuGotoGoal_<std::allocator<void> > PtuGotoGoal;

typedef boost::shared_ptr< ::ptu_control::PtuGotoGoal> PtuGotoGoalPtr;
typedef boost::shared_ptr< ::ptu_control::PtuGotoGoal const> PtuGotoGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ptu_control::PtuGotoGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ptu_control::PtuGotoGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ptu_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::ptu_control::PtuGotoGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3081c5893ca658a36b6caa436091a00d";
  }

  static const char* value(const  ::ptu_control::PtuGotoGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3081c5893ca658a3ULL;
  static const uint64_t static_value2 = 0x6b6caa436091a00dULL;
};

template<class ContainerAllocator>
struct DataType< ::ptu_control::PtuGotoGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ptu_control/PtuGotoGoal";
  }

  static const char* value(const  ::ptu_control::PtuGotoGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ptu_control::PtuGotoGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# goal\n\
float32 pan\n\
float32 tilt\n\
float32 pan_vel\n\
float32 tilt_vel\n\
\n\
";
  }

  static const char* value(const  ::ptu_control::PtuGotoGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ptu_control::PtuGotoGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ptu_control::PtuGotoGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pan);
    stream.next(m.tilt);
    stream.next(m.pan_vel);
    stream.next(m.tilt_vel);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PtuGotoGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ptu_control::PtuGotoGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ptu_control::PtuGotoGoal_<ContainerAllocator> & v) 
  {
    s << indent << "pan: ";
    Printer<float>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<float>::stream(s, indent + "  ", v.tilt);
    s << indent << "pan_vel: ";
    Printer<float>::stream(s, indent + "  ", v.pan_vel);
    s << indent << "tilt_vel: ";
    Printer<float>::stream(s, indent + "  ", v.tilt_vel);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PTU_CONTROL_MESSAGE_PTUGOTOGOAL_H

